import { z } from 'zod';

export const ChannelNameList = z.enum([
  'app.viewer',
  'app.viewerRepos',
  'projects.list',
  'projects.add',
  'projects.open',
  'projects.setTargeting',
  'projects.setLayout',
  'projects.remove',
  'projects.fetch',
  'clone.start',
  'pr.list',
  'pr.view',
  'pr.commits',
  'pr.checkout',
  'pr.branches',
  'pr.create',
  'commits.list',
  'files.changed',
  'files.diff',
  'files.content',
  'trees.get',
  'search.run',
  'symbols.line',
  'symbols.definition',
  'symbols.workspace',
  'symbols.document',
  'comments.list',
  'comments.upsert',
  'comments.delete',
  'viewed.list',
  'viewed.set',
  'sync.run',
  'sync.pendingCount',
  'index.get',
  'log.write',
  'log.getPath',
  'extensions.list',
  'extensions.setEnabled',
  'extensions.install',
  'extensions.dir',
  'grammars.list',
  'theme.getSystemPrefersDark',
  'theme.getTemplateId',
  'theme.setTemplateId',
  'themes.list',
  'locale.getLocaleId',
  'locale.setLocaleId',
  'locales.list',
  'keybindings.getOverrides',
  'keybindings.setOverride',
]);
export type ChannelNameList = z.infer<typeof ChannelNameList>;

export const EventNameList = z.enum([
  'clone.progress',
  'index.status',
  'theme.changed',
  'app.error',
]);
export type EventNameList = z.infer<typeof EventNameList>;
